name: Run Linting
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
            node-version: '8.11.3'
      - name: Install
        run: yarn install
      - name: Lint TypeScript
        run: yarn lint-ts --max-warnings 0
      - name: Lint Styles
        run: yarn lint-style